setwd("/Volumes/Research/WWScripts")

### Counts for 1sec ###
metadata1sec = read.csv("eventcodes1sec.csv")
IDS = length(which(metadata1sec$Event1 == "T"))
print(IDS)
ODS = length(which(metadata1sec$Event1 == "N"))
print(ODS)
Unknown = length(which(metadata1sec$Event1 == "U"))
print(Unknown)
Canon = length(which(metadata1sec$Event1 == "C"))
print(Canon)
NonCanon = length(which(metadata1sec$Event1 == "X"))
print(NonCanon)
Reflex = length(which(metadata1sec$Event1 == "R"))
print(Reflex)
Pause = length(which(metadata1sec$Event1 == "P"))
print(Pause)

### Counts for 2sec ###
metadata2sec = read.csv("eventcodes2sec.csv")
IDS = length(which(metadata2sec$Event1 == "T"))
print(IDS)
ODS = length(which(metadata2sec$Event1 == "N"))
print(ODS)
Unknown = length(which(metadata2sec$Event1 == "U"))
print(Unknown)
Canon = length(which(metadata2sec$Event1 == "C"))
print(Canon)
NonCanon = length(which(metadata2sec$Event1 == "X"))
print(NonCanon)
Reflex = length(which(metadata2sec$Event1 == "R"))
print(Reflex)
Pause = length(which(metadata2sec$Event1 == "P"))
print(Pause)


### Counts for 5sec ###
metadata5sec = read.csv("eventcodes5sec.csv")
IDS = length(which(metadata5sec$Event1 == "T"))
print(IDS)
ODS = length(which(metadata5sec$Event1 == "N"))
print(ODS)
Unknown = length(which(metadata5sec$Event1 == "U"))
print(Unknown)
Canon = length(which(metadata5sec$Event1 == "C"))
print(Canon)
NonCanon = length(which(metadata5sec$Event1 == "X"))
print(NonCanon)
Reflex = length(which(metadata5sec$Event1 == "R"))
print(Reflex)
Pause = length(which(metadata5sec$Event1 == "P"))
print(Pause)
